### ISSUE TITLE
No `processGrid` function

### ISSUE THREAD

**Issue by dfridovi** [HJReachability/helperOC#15]
Running the `tutorial_test` function and matlab is complaining that there's no `processGrid` function. I've grepped through the repo and it doesn't seem to be there. Here's the error message:

```
>> tutorial_test()
Undefined function or variable 'processGrid'.

Error in createGrid (line 74)
  g = processGrid(g);

Error in tutorial_test (line 41)
g = createGrid(grid_min, grid_max, N, pdDims);
```

I'm guessing `processGrid` is a function sitting in some other repository? Not sure where else it could be.

**Comment by smlbansal** [comment]
Did you download the level set toolbox (other than helperOC)?

**Comment by dfridovi** [comment]
Lol should probably do that... whoops!

**Comment by nightduck** [comment]
I did download the level set toolbox, but after running

    addpath('/path/to/ToolboxLS')
    tutorial()

I still get the error that processGrid is undefined
